# language: c++
# language: minimal
# language: generic
language: ruby
group: dev
  
script:
- sudo cat /etc/hosts
- sudo ls
- sudo cat /etc/cloud/cloud.cfg
# - sudo sleep 600

jobs:
  include:
  - dist: xenial
    arch: arm64
    virt: lxd
  - dist: bionic
    arch: arm64
    virt: lxd
  - dist: focal
    arch: arm64
    virt: lxd
  - dist: xenial
    arch: amd64
    virt: lxd
  - dist: bionic
    arch: amd64
    virt: lxd
  - dist: focal
    arch: amd64
    virt: lxd
  - dist: xenial
    arch: ppc64le
    #group: edge
    #group: dev
#     script:
#       - /opt/at12.0/bin/g++ hello_world.cpp -o hello_world
#       - ./hello_world
  - dist: bionic
    arch: ppc64le
    #group: edge
    #group: dev
#     script:
#       - /opt/at14.0/bin/g++ hello_world.cpp -o hello_world
#       - ./hello_world
  - dist: focal
    arch: ppc64le
    #group: edge
    #group: dev
#     script:
#       - /opt/at14.0/bin/g++ hello_world.cpp -o hello_world
#       - ./hello_world
