dist: xenial
install: skip
group: dev
script:
# - uname -a
# - sudo apt update
# - sudo dpkg -l | grep kvm
# - sudo id kvm
- sudo ls /opt


jobs:
  include:
    - dist: xenial
      group: edge
      script:
      - sudo ls /opt/at12.0/bin/
      - /opt/at12.0/bin/gccgo version
    - dist: bionic
      group: edge
      script: 
      - sudo ls /opt/at14.0/bin/
      - /opt/at14.0/bin/gccgo version
    - dist: focal
      group: dev
      script: 
      - sudo ls /opt/at14.0/bin/
      - /opt/at14.0/bin/gccgo version
