dist: xenial
install: skip
script:
- uname -a
# - sudo apt update
# - sudo dpkg -l | grep kvm
# - sudo id kvm
- sudo cat /etc/group


jobs:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
