dist: xenial
install: skip
group: dev
script:
# - uname -a
# - sudo apt update
# - sudo dpkg -l | grep kvm
# - sudo id kvm
- sudo ls /opt


jobs:
  include:
    - dist: xenial
      group: dev
    - dist: bionic
      group: dev
    - dist: focal
      group: dev
